# Generated by Django 2.1 on 2020-06-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(default='https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2162619954,4226478655&fm=26&gp=0.jpg', help_text='图片链接', max_length=120, verbose_name='头像链接'),
        ),
    ]
