# Generated by Django 2.1 on 2020-06-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200607_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(default='https://img1.doubanio.com/view/group_topic/l/public/p289128177.webp', help_text='图片链接', max_length=120, verbose_name='头像链接'),
        ),
    ]
