# Generated by Django 2.1 on 2020-06-23 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200608_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='user.Message', verbose_name='父留言'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image_url',
            field=models.CharField(default='https://thirdqq.qlogo.cn/g?b=oidb&k=5ia1t4Dz2o1DxWzbpKrMic2Q&s=100&t=1592589321', help_text='图片链接', max_length=120, verbose_name='头像链接'),
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
