# Generated by Django 2.1 on 2020-06-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200623_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.AlterField(
            model_name='message',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Message', verbose_name='父留言'),
        ),
        migrations.AlterModelTable(
            name='message',
            table='tb_messages',
        ),
    ]
