# Generated by Django 2.1 on 2020-06-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200607_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('recommend_title', models.CharField(help_text='标题', max_length=150, verbose_name='标题')),
                ('recommend_url', models.URLField(help_text='请填写推荐文章的地址', verbose_name='文章地址')),
            ],
            options={
                'verbose_name': '推荐阅读',
                'verbose_name_plural': '推荐阅读',
                'db_table': 'tb_recommend_read',
            },
        ),
    ]
