# Generated by Django 2.1 on 2020-06-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_recommendread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/', verbose_name='图片链接'),
        ),
    ]
