# Generated by Django 2.1 on 2020-06-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200623_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
