# Generated by Django 2.1 on 2020-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200623_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.ImageField(upload_to='article/%Y%m%d/', verbose_name='文章图片'),
        ),
    ]
